#!/usr/bin/env python3
"""Snapshot the firmware's 11 procedural 35px integration visuals for Entropy."""
import argparse
import subprocess
import tempfile
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('screen_layout', type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
source = args.screen_layout.read_text()
body = 'static void integration_icon_pixel' + source.split('static void integration_icon_pixel', 1)[1].split('static void screen_layout_set_integration_icon', 1)[0]
# Action icons already come from action-icons.bin; only snapshot 1..11.
first = body.index('    if (visual >= EH_ACTION_ICON_FIRST_VISUAL')
last = body.index('    if (visual == 1)', first)
body = body[:first] + body[last:]
c_source = '''#include <stdint.h>\n#include <stdbool.h>\n#include <stdio.h>\n#define EH_ICON_RENDER_SIZE 35\n#define EH_ICON_RENDER_STRIDE 5\n''' + body + '''\nint main(void) {
    for (uint8_t visual = 1; visual <= 11; ++visual) {
        uint8_t bits[175] = {0};
        integration_icon_base(bits, visual);
        if (fwrite(bits, 1, 175, stdout) != 175) return 1;
    }
    return 0;
}\n'''
with tempfile.TemporaryDirectory() as directory:
    src = Path(directory) / 'icons.c'
    exe = Path(directory) / 'icons'
    src.write_text(c_source)
    subprocess.run(['cc', '-std=c99', '-Wall', '-Werror', '-Wno-unused-function', str(src), '-o', str(exe)], check=True)
    raw = subprocess.check_output([str(exe)])
assert len(raw) == 11 * 175
packed = bytearray()
for icon in range(11):
    rows = raw[icon * 175:(icon + 1) * 175]
    bits = [bool(rows[y * 5 + x // 8] & (0x80 >> (x % 8))) for y in range(35) for x in range(35)]
    bitmap = bytes(sum(0x80 >> j for j in range(8) if i + j < len(bits) and bits[i + j]) for i in range(0, len(bits), 8))
    assert len(bitmap) == 154 and any(bitmap)
    packed.extend(bitmap)
(root / 'assets/integration-icons.bin').write_bytes(packed)
(root / 'src/integration_icons.rs').write_text(
    '// Generated by tools/sync_integration_icons.py from firmware screen_layout.c.\n'
    'pub(crate) const INTEGRATION_ICON_COUNT: usize = 11;\n'
    'pub(crate) fn bitmap(index: usize) -> [u8; 154] {\n'
    '    let bytes = include_bytes!("../assets/integration-icons.bin");\n'
    '    let mut out = [0; 154];\n'
    '    out.copy_from_slice(&bytes[index * 154..(index + 1) * 154]);\n'
    '    out\n}\n'
)
