#!/usr/bin/env python3
"""Copy the native 35x35 firmware built-in artwork into Entropy's picker."""
import argparse
import re
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument('firmware_header', type=Path)
parser.add_argument('layer_header', type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
source = args.firmware_header.read_text()
blocks = re.findall(r'\{ // ([a-z_]+)\n(.*?)\n    \},', source, re.S)
assert len(blocks) == 20, f'Unexpected firmware icon count: {len(blocks)}'
names = []
bitmaps = []
for name, body in blocks:
    data = bytes(int(value, 16) for value in re.findall(r'0x([0-9a-f]{2})', body))
    assert len(data) == 154, (name, len(data))
    names.append(name)
    bitmaps.append(data)
for name, body in re.findall(r'static const uint8_t (layer_(?:prev|next)_icon)\[154\] = \{(.*?)\};', args.layer_header.read_text(), re.S):
    data = bytes(int(value, 16) for value in re.findall(r'0x([0-9A-Fa-f]{2})', body))
    assert len(data) == 154, (name, len(data))
    names.append(name)
    bitmaps.append(data)
assert len(names) == 22
(root / 'assets/firmware-builtin-icons.bin').write_bytes(b''.join(bitmaps))
(root / 'src/firmware_builtin_icons.rs').write_text(
    '// Generated by tools/sync_firmware_builtin_icons.py; indexes match firmware header.\n'
    'pub(crate) const FIRMWARE_ICON_COUNT: usize = 22;\n'
    'pub(crate) const FIRMWARE_ICON_KEYS: [&str; FIRMWARE_ICON_COUNT] = [\n'
    + ''.join(f'    "display_settings.pictogram_firmware_{name}",\n' for name in names)
    + '];\n'
    'pub(crate) fn bitmap(index: usize) -> [u8; 154] {\n'
    '    let bytes = include_bytes!("../assets/firmware-builtin-icons.bin");\n'
    '    let mut out = [0; 154];\n'
    '    out.copy_from_slice(&bytes[index * 154..(index + 1) * 154]);\n'
    '    out\n}\n'
)
print(', '.join(names))
