// Generated by tools/generate_action_icons.py. Do not edit by hand.
pub(crate) const ACTION_ICON_COUNT: usize = 117;
pub(crate) const ACTION_ICON_KEYS: [&str; ACTION_ICON_COUNT] = [
    "display_settings.pictogram_builtin_action_link",
    "display_settings.pictogram_builtin_action_plus",
    "display_settings.pictogram_builtin_action_search",
    "display_settings.pictogram_builtin_action_arrow_left",
    "display_settings.pictogram_builtin_action_arrow_right",
    "display_settings.pictogram_builtin_action_history",
    "display_settings.pictogram_builtin_action_move_left",
    "display_settings.pictogram_builtin_action_move_right",
    "display_settings.pictogram_builtin_action_maximize",
    "display_settings.pictogram_builtin_action_move_down",
    "display_settings.pictogram_builtin_action_move_up",
    "display_settings.pictogram_builtin_action_bookmark",
    "display_settings.pictogram_builtin_action_download",
    "display_settings.pictogram_builtin_action_square_pen",
    "display_settings.pictogram_builtin_action_save",
    "display_settings.pictogram_builtin_action_printer",
    "display_settings.pictogram_builtin_action_focus",
    "display_settings.pictogram_builtin_action_zoom_out",
    "display_settings.pictogram_builtin_action_zoom_in",
    "display_settings.pictogram_builtin_action_command",
    "display_settings.pictogram_builtin_action_folder_open",
    "display_settings.pictogram_builtin_action_terminal",
    "display_settings.pictogram_builtin_action_panel_left",
    "display_settings.pictogram_builtin_action_panel_bottom",
    "display_settings.pictogram_builtin_action_message_square_code",
    "display_settings.pictogram_builtin_action_bug",
    "display_settings.pictogram_builtin_action_bug_off",
    "display_settings.pictogram_builtin_action_text_cursor_input",
    "display_settings.pictogram_builtin_action_replace",
    "display_settings.pictogram_builtin_action_folder_search",
    "display_settings.pictogram_builtin_action_files",
    "display_settings.pictogram_builtin_action_git_branch",
    "display_settings.pictogram_builtin_action_list_filter",
    "display_settings.pictogram_builtin_action_mouse_pointer_2",
    "display_settings.pictogram_builtin_action_arrow_up",
    "display_settings.pictogram_builtin_action_arrow_down",
    "display_settings.pictogram_builtin_action_file_plus",
    "display_settings.pictogram_builtin_action_file_pen",
    "display_settings.pictogram_builtin_action_square_terminal",
    "display_settings.pictogram_builtin_action_blocks",
    "display_settings.pictogram_builtin_action_paintbrush",
    "display_settings.pictogram_builtin_action_eraser",
    "display_settings.pictogram_builtin_action_crop",
    "display_settings.pictogram_builtin_action_lasso",
    "display_settings.pictogram_builtin_action_square_dashed",
    "display_settings.pictogram_builtin_action_pipette",
    "display_settings.pictogram_builtin_action_bandage",
    "display_settings.pictogram_builtin_action_type",
    "display_settings.pictogram_builtin_action_scan",
    "display_settings.pictogram_builtin_action_undo",
    "display_settings.pictogram_builtin_action_redo",
    "display_settings.pictogram_builtin_action_copy",
    "display_settings.pictogram_builtin_action_mouse_pointer",
    "display_settings.pictogram_builtin_action_select_all",
    "display_settings.pictogram_builtin_action_paste",
    "display_settings.pictogram_builtin_action_layers_plus",
    "display_settings.pictogram_builtin_action_group",
    "display_settings.pictogram_builtin_action_blend",
    "display_settings.pictogram_builtin_action_eye",
    "display_settings.pictogram_builtin_action_component",
    "display_settings.pictogram_builtin_action_list_restart",
    "display_settings.pictogram_builtin_action_layers",
    "display_settings.pictogram_builtin_action_scissors",
    "display_settings.pictogram_builtin_action_corner_up_left",
    "display_settings.pictogram_builtin_action_corner_up_right",
    "display_settings.pictogram_builtin_action_move_horizontal",
    "display_settings.pictogram_builtin_action_move_vertical",
    "display_settings.pictogram_builtin_action_hand",
    "display_settings.pictogram_builtin_action_play",
    "display_settings.pictogram_builtin_action_step_back",
    "display_settings.pictogram_builtin_action_step_forward",
    "display_settings.pictogram_builtin_action_flag",
    "display_settings.pictogram_builtin_action_flag_triangle_right",
    "display_settings.pictogram_builtin_action_pause",
    "display_settings.pictogram_builtin_action_skip_back",
    "display_settings.pictogram_builtin_action_skip_forward",
    "display_settings.pictogram_builtin_action_frame",
    "display_settings.pictogram_builtin_action_rectangle_horizontal",
    "display_settings.pictogram_builtin_action_pen_tool",
    "display_settings.pictogram_builtin_action_expand",
    "display_settings.pictogram_builtin_action_circle",
    "display_settings.pictogram_builtin_action_line_squiggle",
    "display_settings.pictogram_builtin_action_scaling",
    "display_settings.pictogram_builtin_action_copy_plus",
    "display_settings.pictogram_builtin_action_ungroup",
    "display_settings.pictogram_builtin_action_image_plus",
    "display_settings.pictogram_builtin_action_send_to_back",
    "display_settings.pictogram_builtin_action_bring_to_front",
    "display_settings.pictogram_builtin_action_scan_line",
    "display_settings.pictogram_builtin_action_pencil",
    "display_settings.pictogram_builtin_action_move",
    "display_settings.pictogram_builtin_action_rotate_cw",
    "display_settings.pictogram_builtin_action_keyboard",
    "display_settings.pictogram_builtin_action_package_plus",
    "display_settings.pictogram_builtin_action_scan_dashed",
    "display_settings.pictogram_builtin_action_eye_off",
    "display_settings.pictogram_builtin_action_panel_right",
    "display_settings.pictogram_builtin_action_view_front",
    "display_settings.pictogram_builtin_action_view_right",
    "display_settings.pictogram_builtin_action_view_top",
    "display_settings.pictogram_builtin_action_box",
    "display_settings.pictogram_builtin_action_camera",
    "display_settings.pictogram_builtin_action_rotate_ccw",
    "display_settings.pictogram_builtin_action_route",
    "display_settings.pictogram_builtin_action_circle_arrow_up",
    "display_settings.pictogram_builtin_action_circle_arrow_down",
    "display_settings.pictogram_builtin_action_arrow_down_to_line",
    "display_settings.pictogram_builtin_action_arrow_up_to_line",
    "display_settings.pictogram_builtin_action_mic_off",
    "display_settings.pictogram_builtin_action_headphones",
    "display_settings.pictogram_builtin_action_volume_x",
    "display_settings.pictogram_builtin_action_volume_2",
    "display_settings.pictogram_builtin_action_incognito",
    "display_settings.pictogram_builtin_action_code",
    "display_settings.pictogram_builtin_action_book_open",
    "display_settings.pictogram_builtin_action_file_output",
    "display_settings.pictogram_builtin_action_audio_lines",
];
pub(crate) fn bitmap(index: usize) -> [u8; 154] {
    let bytes = include_bytes!("../assets/action-icons.bin");
    let mut out = [0; 154];
    let start = index * 154;
    out.copy_from_slice(&bytes[start..start + 154]);
    out
}
pub(crate) fn preset_visual(preset_id: &str, layer: usize, control: usize) -> u8 {
    let icons: &[&[u8; 12]] = match preset_id {
        "google_chrome" => &[
            &[12, 13, 14, 15, 16, 17, 18, 19, 20, 12, 21, 22], // Browsing
            &[23, 24, 17, 25, 26, 27, 28, 29, 30, 14, 29, 30], // Pages
        ],
        "visual_studio_code" => &[
            &[31, 32, 33, 34, 35, 36, 37, 38, 39, 32, 18, 19], // Coding
            &[14, 40, 41, 42, 43, 44, 45, 22, 21, 14, 46, 47], // Search
            &[48, 32, 26, 49, 33, 50, 34, 41, 51, 26, 18, 19], // Files & terminal
        ],
        "adobe_photoshop" => &[
            &[45, 52, 53, 54, 55, 56, 57, 58, 59, 60, 29, 30], // Tools
            &[61, 62, 63, 26, 64, 65, 63, 66, 28, 60, 29, 30], // Editing
            &[67, 63, 68, 69, 70, 71, 72, 73, 49, 63, 18, 19], // Layers
        ],
        "adobe_premiere_pro" => &[
            &[45, 74, 75, 76, 77, 78, 79, 30, 80, 80, 81, 82], // Editing
            &[83, 84, 81, 85, 82, 23, 74, 61, 62, 85, 15, 16], // Timeline
            &[26, 32, 48, 63, 66, 65, 86, 87, 0, 26, 30, 29],  // Project
        ],
        "figma" => &[
            &[45, 88, 89, 90, 59, 91, 28, 31, 61, 31, 29, 30], // Design
            &[92, 93, 79, 94, 65, 63, 66, 95, 68, 96, 29, 30], // Arrange
            &[96, 71, 97, 21, 22, 98, 99, 100, 39, 68, 21, 22], // Layers
        ],
        "adobe_illustrator" => &[
            &[45, 64, 90, 59, 89, 92, 52, 101, 74, 68, 29, 30], // Tools
            &[68, 96, 63, 66, 61, 62, 65, 95, 73, 68, 21, 22],  // Objects
            &[48, 32, 26, 49, 27, 14, 86, 87, 0, 26, 29, 30],   // Documents
        ],
        "blender" => &[
            &[102, 103, 94, 104, 105, 14, 69, 61, 62, 28, 29, 30], // Modeling
            &[65, 106, 72, 107, 107, 70, 34, 108, 39, 28, 29, 30], // Selection
            &[109, 110, 111, 112, 113, 28, 91, 14, 108, 28, 114, 103], // Views
        ],
        "visual_studio" => &[
            &[26, 14, 40, 61, 62, 63, 66, 65, 39, 26, 30, 29], // Editing
            &[37, 38, 82, 81, 16, 0, 0, 0, 0, 37, 15, 16],     // Debugging
            &[48, 32, 49, 44, 31, 0, 0, 0, 0, 31, 21, 22],     // Files
        ],
        "intellij_idea" => &[
            &[26, 14, 61, 62, 63, 66, 65, 76, 0, 26, 30, 29], // Coding
            &[14, 42, 40, 44, 31, 0, 0, 0, 0, 14, 21, 22],    // Navigation
            &[37, 80, 48, 32, 49, 0, 0, 0, 0, 26, 21, 22],    // Run & files
        ],
        "pycharm" => &[
            &[26, 14, 61, 62, 63, 66, 65, 76, 0, 26, 30, 29], // Coding
            &[14, 42, 40, 44, 31, 0, 0, 0, 0, 14, 21, 22],    // Navigation
            &[37, 80, 48, 32, 49, 0, 0, 0, 0, 26, 21, 22],    // Run & files
        ],
        "obs_studio" => &[
            &[61, 62, 14, 63, 103, 70, 15, 46, 16, 70, 47, 46], // Sources
            &[63, 66, 22, 21, 99, 98, 91, 47, 28, 91, 21, 22],  // Source order
        ],
        "discord" => &[
            &[115, 14, 116, 117, 118, 119, 0, 0, 0, 115, 46, 47], // Navigation
            &[120, 121, 0, 0, 0, 0, 0, 0, 0, 0, 122, 123],        // Voice
        ],
        "firefox" => &[
            &[12, 13, 14, 15, 16, 17, 20, 19, 18, 12, 21, 22], // Browsing
            &[23, 24, 17, 124, 26, 125, 23, 28, 126, 28, 29, 30], // Reading
        ],
        "audacity" => &[
            &[80, 85, 81, 85, 82, 86, 87, 61, 62, 14, 29, 30], // Audio
            &[74, 63, 66, 95, 65, 26, 48, 32, 127, 128, 21, 22], // Clip editing
        ],
        _ => return 0,
    };
    let index = if control < 9 {
        control
    } else if (12..15).contains(&control) {
        control - 3
    } else {
        return 0;
    };
    icons.get(layer).map_or(0, |icons| icons[index])
}
