// Generated by tools/sync_firmware_builtin_icons.py; indexes match firmware header.
pub(crate) const FIRMWARE_ICON_COUNT: usize = 22;
pub(crate) const FIRMWARE_ICON_KEYS: [&str; FIRMWARE_ICON_COUNT] = [
    "display_settings.pictogram_firmware_brightness_down",
    "display_settings.pictogram_firmware_brightness_up",
    "display_settings.pictogram_firmware_control_panel",
    "display_settings.pictogram_firmware_computer",
    "display_settings.pictogram_firmware_web_search",
    "display_settings.pictogram_firmware_mail",
    "display_settings.pictogram_firmware_calculator",
    "display_settings.pictogram_firmware_volume_down",
    "display_settings.pictogram_firmware_home",
    "display_settings.pictogram_firmware_insert",
    "display_settings.pictogram_firmware_end",
    "display_settings.pictogram_firmware_delete",
    "display_settings.pictogram_firmware_screenshot",
    "display_settings.pictogram_firmware_mouse_left",
    "display_settings.pictogram_firmware_mouse_middle",
    "display_settings.pictogram_firmware_mouse_right",
    "display_settings.pictogram_firmware_wheel_up",
    "display_settings.pictogram_firmware_wheel_down",
    "display_settings.pictogram_firmware_page_up",
    "display_settings.pictogram_firmware_page_down",
    "display_settings.pictogram_firmware_layer_prev_icon",
    "display_settings.pictogram_firmware_layer_next_icon",
];
pub(crate) fn bitmap(index: usize) -> [u8; 154] {
    let bytes = include_bytes!("../assets/firmware-builtin-icons.bin");
    let mut out = [0; 154];
    out.copy_from_slice(&bytes[index * 154..(index + 1) * 154]);
    out
}
