// Generated by tools/sync_integration_icons.py from firmware screen_layout.c.
pub(crate) const INTEGRATION_ICON_COUNT: usize = 11;
pub(crate) fn bitmap(index: usize) -> [u8; 154] {
    let bytes = include_bytes!("../assets/integration-icons.bin");
    let mut out = [0; 154];
    out.copy_from_slice(&bytes[index * 154..(index + 1) * 154]);
    out
}
